/**
 * SOLUTIONS 07 — Recursion and backtracking
 */

/**
 * PROBLEM 1 — Subsets
 *
 * NARRATION:
 *   "Each element is an independent binary choice: in or out. That's 2ⁿ
 *    combinations, so the output alone is exponential and no algorithm can
 *    beat that. I'll walk the array making both choices at each index."
 *
 * COMPLEXITY: O(n · 2ⁿ) time — 2ⁿ subsets, each O(n) to copy.
 *             O(n) auxiliary space for the recursion and the path (excluding
 *             the output, which is inherently O(n · 2ⁿ)). Distinguishing
 *             auxiliary space from output space is a nice precision point.
 *
 * `[...path]` IS MANDATORY. `path` is mutated on the way back up, so pushing it
 * directly gives you 2ⁿ references to one array that ends up empty. Say the
 * reason as you type the spread.
 *
 * THE ITERATIVE VERSION is often easier to explain and has no recursion at all:
 * start with [[]]; for each num, append `existing.map(s => [...s, num])`.
 * Both are O(n · 2ⁿ). Offering the choice reads well.
 */
export function subsets(nums: number[]): number[][] {
  const results: number[][] = [];
  const path: number[] = [];

  function backtrack(index: number): void {
    if (index === nums.length) {
      results.push([...path]); // copy — path keeps mutating
      return;
    }

    // Choice A: skip nums[index]
    backtrack(index + 1);

    // Choice B: take nums[index]
    path.push(nums[index]!);
    backtrack(index + 1);
    path.pop(); // undo
  }

  backtrack(0);
  return results;
}

/**
 * PROBLEM 2 — Permutations
 *
 * NARRATION:
 *   "n choices for the first slot, n-1 for the second, and so on — n!
 *    orderings. I'll track which indices are used so I never place the same
 *    element twice, and undo the mark as I unwind."
 *
 * COMPLETXITY: O(n · n!) time — n! permutations, O(n) to copy each.
 *              O(n) auxiliary space.
 *
 * `used: boolean[]` BEATS A SET here: array indexing is cheaper than Set
 * hashing, and it naturally distinguishes duplicate VALUES at different
 * indices — which is what you need for the duplicates follow-up.
 *
 * THE DUPLICATES FOLLOW-UP: sort first, then skip candidate `i` when
 * `nums[i] === nums[i-1] && !used[i-1]`. The `!used[i-1]` is the subtle half:
 * it means the identical earlier copy is NOT currently in the path, so using
 * this one would produce a permutation already generated by the branch that
 * took the earlier copy. Without it you also wrongly prune valid permutations
 * that legitimately contain both copies. Being able to explain that condition
 * is a strong signal.
 */
export function permutations(nums: number[]): number[][] {
  const results: number[][] = [];
  const path: number[] = [];
  const used = new Array<boolean>(nums.length).fill(false);

  function backtrack(): void {
    if (path.length === nums.length) {
      results.push([...path]);
      return;
    }

    for (let i = 0; i < nums.length; i += 1) {
      if (used[i]) continue;

      used[i] = true;
      path.push(nums[i]!);

      backtrack();

      path.pop();
      used[i] = false;
    }
  }

  backtrack();
  return results;
}

/**
 * PROBLEM 3 — Combination Sum
 *
 * THE KEY DECISION — say this out loud, it is the whole problem:
 *   "Combinations are unordered, so I must not generate [2,3] and [3,2] as two
 *    answers. I'll enforce non-decreasing order by passing a start index and
 *    never looking backwards. That makes every combination reachable by exactly
 *    one path through the search tree, so uniqueness is structural rather than
 *    something I have to de-duplicate afterwards."
 *
 * REUSE: recurse with `i`, not `i + 1`. That single character is the difference
 * between "may reuse a candidate" and "may not" — worth pointing at explicitly,
 * because the interviewer's follow-up is usually exactly that variant.
 *
 * COMPLEXITY: O(n^(target/min)) in the worst case — exponential, bounded by how
 * deep the tree can go before the remaining target goes negative. Do not
 * pretend this has a tidy polynomial bound; saying "exponential, bounded by
 * target divided by the smallest candidate" is the honest, precise answer.
 *
 * THE PRUNE: sorting lets you `break` rather than `continue` once a candidate
 * exceeds the remaining target — everything after it is larger too. Real
 * speedup, one line, and it shows you thought about the search space.
 *
 * `target === 0` returns `[[]]`: exactly one way to make nothing, the empty
 * combination. That is a genuine edge case worth confirming with the
 * interviewer rather than assuming.
 */
export function combinationSum(candidates: number[], target: number): number[][] {
  const results: number[][] = [];
  const path: number[] = [];
  const sorted = [...candidates].sort((a, b) => a - b);

  function backtrack(start: number, remaining: number): void {
    if (remaining === 0) {
      results.push([...path]);
      return;
    }

    for (let i = start; i < sorted.length; i += 1) {
      const candidate = sorted[i]!;

      // Sorted, so every later candidate is at least this large — stop, don't skip.
      if (candidate > remaining) break;

      path.push(candidate);
      // `i`, not `i + 1`: the same candidate may be reused.
      backtrack(i, remaining - candidate);
      path.pop();
    }
  }

  backtrack(0, target);
  return results;
}
